# Generated by Django 2.2.3 on 2019-07-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyleApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='state',
        ),
    ]
