# Generated by Django 2.2.3 on 2019-07-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyleApp', '0002_remove_branches_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='state',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
