# Generated by Django 2.2.3 on 2019-07-18 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fyleApp', '0004_auto_20190717_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='bank_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branches',
            name='bank_id',
            field=models.BigIntegerField(),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
