# Generated by Django 2.2.3 on 2019-07-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyleApp', '0006_auto_20190718_2325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branches',
        ),
    ]
